
DROP TABLE IF EXISTS Room_Feature;
DROP TABLE IF EXISTS Favorit_Rooms;

DROP TABLE IF EXISTS Local_Admin;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Rooms;
DROP TABLE IF EXISTS Building;
DROP TABLE IF EXISTS Campus;